### ISSUE TITLE
Numbers are floating.

### ISSUE THREAD

**Issue by grapefruitXLJ** [lobachevzky/mujoco#2]
Thank you for the codes you share with us. I successfully install this module but when i run 'examples/markers_demo.py', numbers are floating like this:
![2018-01-16 09-19-22](https://user-images.githubusercontent.com/29224761/34967609-123de3b2-fa9f-11e7-83a9-bc96ce757bb7.png)
A string of data keeps floating.

**Comment by lobachevzky** [comment]
Hi @grapefruitXLJ. Those floating numbers are intentional. This script is designed to emulate the [`markers_demo.py`](https://github.com/openai/mujoco-py/blob/master/examples/markers_demo.py) that comes with mujoco-py.  It also demonstrates what you can do with `render(labels=...)`, namely add text to a specified location on a particular camera.

**Comment by grapefruitXLJ** [comment]
@lobachevzkyOh~I see~Thank you!

**Comment by grapefruitXLJ** [comment]
@lobachevzky I see,Thank you~
